sendgrid/sendgrid-csharp

SendGrid/SendGridMail/ISendGrid.cs, SendGrid/SendGridMail/SendGrid.cs, SendGrid/SendGridMail/StreamedFileBody.cs
I'm generating an image and then transferring it to memory stream right away.  This prevents you from having to create a file if you already have a memory stream.
=> Adding ability to embed an image via a memory stream.  

SendGrid/SendGridMail/Mail.csproj, SendGrid/SendGridMail/Transport/ErrorChecker.cs, SendGrid/SendGridMail/Transport/Web.cs, SendGrid/Tests/Tests.csproj, SendGrid/Tests/Transport/TestErrorChecker.cs
Hi,
I had to track down a production issue around handling of the bad username / password scenario and did a little refactoring to enable me to write a test to prove that the SendGrid client was handling this properly.
If anyone can point me towards more response XML messages - I'm more than happy to flesh out the test suite with other use cases.
Howard
=> Refactor error handling.

README.md
Added code for show how to use template in the email
=> How to use template email

SendGrid/SendGrid/Client.cs, SendGrid/SendGrid/SendGrid.csproj, SendGrid/SendGrid/packages.config
https://github.com/sendgrid/sendgrid-csharp/issues/344
=> Remove  SendGrid.CSharp.HTTP.Client

src/SendGrid/Helpers/Mail/MailHelper.cs, tests/SendGrid.Tests/Integration.cs
Fixes https://github.com/sendgrid/sendgrid-csharp/issues/396
=> Issue #396 - Fix MailHelper null issue

CODE_OF_CONDUCT.md
=> Fix #553: Add a Code Of Conduct

LICENSE.txt
Updated the `LICENSE.txt` file to have the correct date range: 2016-<current year, 2017 in this case>.
Resolves #605
=> Updated the LICENSE.txt file to have the correct date range

tests/SendGrid.Tests/RequiredFilesExistTest.cs
- Added unittest to check for specific repo files mentioned in #607
=> Added unittest to check for specific repo files

README.md
#653 - Test Environment Variable Setup Instruction on Windows 10
-  It improves the instructions to setup environment variables
=> Improved environment variable setup instructions

USAGE.md
Update Create Template Version Docs as per sendgrid support request 'https://support.sendgrid.com/hc/en-us/requests/1382463?flash_digest=6a468b8f19e66f1d040d6363d45d233430c64c03'
Fixes #668
=> Update Create Template Version Docs as per sendgrid support request

README.md
- Added Open Source code helper tag 
=> update readme tags

USAGE.md
=> Fixed typo in Usage.md

.travis.yml
[611](https://github.com/sendgrid/sendgrid-csharp/issues/611)
Added CodeCov support [611](https://github.com/sendgrid/sendgrid-csharp/issues/611)
=> added codecov support

CONTRIBUTING.md, README.md
Resolves #619
- Add a "Code Reviews" section on CONTRIBUTING.md
- Link the header in the Contributing.md Table of Contents
- Add a link to the README.md file
=> Add Code Review to Contributing.md

src/SendGrid/Helpers/Mail/MailHelper.cs, src/SendGrid/Helpers/Mail/Model/ASM.cs, src/SendGrid/Helpers/Mail/Model/Attachment.cs, src/SendGrid/Helpers/Mail/Model/BCCSettings.cs, src/SendGrid/Helpers/Mail/Model/BypassListManagement.cs, src/SendGrid/Helpers/Mail/Model/ClickTracking.cs, src/SendGrid/Helpers/Mail/Model/Content.cs, src/SendGrid/Helpers/Mail/Model/EmailAddress.cs, src/SendGrid/Helpers/Mail/Model/FooterSettings.cs, src/SendGrid/Helpers/Mail/Model/Ganalytics.cs, src/SendGrid/Helpers/Mail/Model/HtmlContent.cs, src/SendGrid/Helpers/Mail/Model/MailSettings.cs, src/SendGrid/Helpers/Mail/Model/OpenTracking.cs, src/SendGrid/Helpers/Mail/Model/Personalization.cs, src/SendGrid/Helpers/Mail/Model/SandboxMode.cs, src/SendGrid/Helpers/Mail/Model/SpamCheck.cs, src/SendGrid/Helpers/Mail/Model/SubscriptionTracking.cs, src/SendGrid/Helpers/Mail/Model/TrackingSettings.cs, src/SendGrid/Helpers/Mail/SendGridMessage.cs, src/SendGrid/ISendGridClient.cs, src/SendGrid/Reliability/ReliabilitySettings.cs, src/SendGrid/Reliability/RetryDelegatingHandler.cs, src/SendGrid/Response.cs, src/SendGrid/SendGrid.csproj, src/SendGrid/SendGrid.ruleset, src/SendGrid/SendGridClient.cs, src/SendGrid/SendGridClientOptions.cs, src/SendGrid/stylecop.json, tests/SendGrid.Tests/Integration.cs
- This change eliminates all build warnings.  There are a lot of changes, but mostly they are trivial.  It may be easiest to review them one commit at a time.
=> Fix build warnings

src/SendGrid/SendGridClient.cs
- Fix for issue #697 https://github.com/sendgrid/sendgrid-csharp/issues/697#event-1681681007
- Added virtual tag to a method that should be virtual.
- Tested, it fixes the bug we have discussed in issue #697
=> Fixed virtual bug

src/SendGrid/Helpers/Mail/SendGridMessage.cs, src/SendGrid/SendGridClient.cs, tests/SendGrid.Tests/Helpers/Mail/SendGridMessageTests.cs, tests/SendGrid.Tests/Integration.cs, tests/SendGrid.Tests/Reliability/RetryDelegatingHandlerTests.cs
- Cleans up some formatting of source to remove compiler warnings
- Tidy some asserts to fix xunit warnings
=> Update to remove compiler warnings based on stylecop/xunit

examples/mail/mail.cs
- [ x] I have made a material change to the repo (functionality, testing, spelling, grammar)
- [x ] I have read the [Contribution Guide] and my PR follows them.
- [x ] I updated my branch with the master branch.
- fixes a typo in the mail example
- 
=> fixed typo in mail example

.github/PULL_REQUEST_TEMPLATE, CONTRIBUTING.md
- Update contribution to use Gitflow workflow
=> Update contribution to use Gitflow workflow

USAGE.md, examples/templates/templates.cs
Fixes #759
- Add `generations` URI parameter to `USAGE.md` to demonstrate how to use this API call to retrieve all templates (dynamic & legacy)
- Add `generations` URI parameter to corresponding `/example` file to demonstrate how to use this API call to retrieve all templates (dynamic & legacy)
=> docs: Update documentation for retrieving all templates

.travis.yml
=> chore: fix travis path for automated deploy

ExampleNet45ASPNetProject/SendGrid.ASPSamples/Service/SendGridEmailService.cs
- Fix CC being added as BCC in csharp sample
=> docs: Fix CC being added as BCC in csharp sample

src/SendGrid/Helpers/Mail/SendGridMessage.cs
Fixes https://github.com/sendgrid/sendgrid-csharp/issues/406
=> fix: refactor and fix personalization inserts/updates

src/SendGrid/EllipticCurve/LICENSE, src/SendGrid/EllipticCurve/README.md, src/SendGrid/EllipticCurve/curve.cs, src/SendGrid/EllipticCurve/ecdsa.cs, src/SendGrid/EllipticCurve/math.cs, src/SendGrid/EllipticCurve/point.cs, src/SendGrid/EllipticCurve/publickey.cs, src/SendGrid/EllipticCurve/signature.cs, src/SendGrid/EllipticCurve/utils/base.cs, src/SendGrid/EllipticCurve/utils/binary.cs, src/SendGrid/EllipticCurve/utils/bytes.cs, src/SendGrid/EllipticCurve/utils/der.cs, src/SendGrid/EllipticCurve/utils/integer.cs, src/SendGrid/EllipticCurve/utils/string.cs
=> feat: add Elliptic Curve code and utilities

CHANGELOG.md, CONTRIBUTING.md, ExampleNet45ASPNetProject/README.md, README.md, TROUBLESHOOTING.md, USAGE.md, USE_CASES.md, src/SendGrid/Helpers/Mail/README.md
- Edit *.md files through Grammarly service to improve Spelling and Grammar.
=> docs: Run *.md documents through Grammer.ly

src/SendGrid/SendGrid.csproj
Resolves #1087
Bump ecdsa-dotnet version to 1.3.1
=> chore: bump ecdsa-dotnet version

src/SendGrid.Extensions.DependencyInjection/SendGrid.Extensions.DependencyInjection.csproj
Disable [Public Signing](https://github.com/dotnet/runtime/blob/main/docs/project/public-signing.md)
=> fix: Strong name signature could not be verified

src/SendGrid.Extensions.DependencyInjection/SendGrid.Extensions.DependencyInjection.csproj
bump to publish new version of of [SendGrid.Extensions.DependencyInjection](https://www.nuget.org/packages/SendGrid.Extensions.DependencyInjection/) on NuGet
=> chore: bump SendGrid.Extensions.DependencyInjection from 1.0.0 to 1.0.1

README.md
Fixes #1124 
- Replaced broken links
=> docs: Updated broken Readme.md links 

.github/workflows/test-and-deploy.yml
=> fix:  update deployment pipeline to add signing step

LICENSE
=> chore: Update LICENSE (#1193)

.github/workflows/test-and-deploy.yml
Added workflow for importing certificate and publish to nuget
=> chore: added import-certificate workflow

.github/workflows/test-and-deploy.yml
Import-certificate added as prerequisite for deploy
=> chore: import-certificate added as prerequisite for deploy

.github/workflows/test-and-deploy.yml
=> chore: Update test-and-deploy.yml

.github/workflows/test-and-deploy.yml
=> chore: adding skip-duplicate flag

.github/workflows/test-and-deploy.yml
=> chore: corrected nuget push
