SendGrid/SendGridMail/SendGrid.cs, SendGrid/Tests/TestSendgrid.cs
I've spent quite some time trying to find "test" send mode for SendGrid. I've implemented "SendToSink" flag which some may find very useful. When it is set to true, the message is sent to *user*\_at\_*host*@sink.sendgrid.net, instead of user@host. 
Reference: https://github.com/sendgrid/docs/issues/83
=> Sink host introduced

README.md
Code sample had a `ver` instead of `var`. Fixed.
=> Fixed code samples

CONTRIBUTING.md
Hello!
Just getting my feet wet and ran into this. The example code checks for the "SENDGRID_APIKEY" environment variable, so I thought the documentation should reflect that. I know this is minor.
=> Align contributing guidelines to actual example code

ExampleCoreProject/Example.cs, ExampleNet45Project/Example.cs, SendGrid.sln, src/SendGrid/SendGridClient.cs, src/SendGrid/project.json, tests/SendGrid.Tests/Integration.cs
Changed SendGridClient to keep/reuse HttpClient instance 
Removed obsolete properties and parameters (that cannot be re-set on the HttpClient)
Modified unit tests to pass custom headers to SendGridClient constructor
Change in Examples to avoid exception when there is no groups and correct text message.
=> #405 reuse http client

src/SendGrid/SendGridClient.cs, tests/SendGrid.Tests/Integration.cs
SendGridClient.SendEmailAsync now throws original exception instead of swallowing and reporting http status 200.
In order to make the client unit testable for underlying exceptions thrown when making http requests, there is now a new constructor overload which takes an HttpClient object as one of the parameters.
=> Issue #358: SendGridClient.SendEmailAsync now throws original exception

CONTRIBUTING.md
Please download Prism stable version v0.6.xx as integration test are written against stable versions only. Latest alpah version has different commands to serve swagger file
=> Prism versions for integration tests

src/SendGrid/Helpers/Mail/SendGridMessage.cs, tests/SendGrid.Tests/Integration.cs
Pull request for [#408](https://github.com/sendgrid/sendgrid-csharp/issues/408). Added support for the SetFrom,  AddTo, AddBc, and AddCc overload method. 
I am throwing exception if email address is blank or empty. Let me know if checks is not required in library.
=> AddTo, AddBcc, AddCc and SetFrom that just takes an email and name #408

USE_CASES.md
USE_CASES.md to demonstrate how to Manipulate Personalizations
=> Manipulate Personalizations

.gitignore, src/SendGrid/Helpers/Mail/Model/ASM.cs, src/SendGrid/Helpers/Mail/Model/Attachment.cs, src/SendGrid/Helpers/Mail/Model/BCCSettings.cs, src/SendGrid/Helpers/Mail/Model/BypassListManagement.cs, src/SendGrid/Helpers/Mail/Model/ClickTracking.cs, src/SendGrid/Helpers/Mail/Model/Content.cs, src/SendGrid/Helpers/Mail/Model/EmailAddress.cs, src/SendGrid/Helpers/Mail/Model/FooterSettings.cs, src/SendGrid/Helpers/Mail/Model/Ganalytics.cs, src/SendGrid/Helpers/Mail/Model/HtmlContent.cs, src/SendGrid/Helpers/Mail/Model/MailSettings.cs, src/SendGrid/Helpers/Mail/Model/OpenTracking.cs, src/SendGrid/Helpers/Mail/Model/Personalization.cs, src/SendGrid/Helpers/Mail/Model/SandboxMode.cs, src/SendGrid/Helpers/Mail/Model/SpamCheck.cs, src/SendGrid/Helpers/Mail/Model/SubscriptionTracking.cs, src/SendGrid/Helpers/Mail/Model/TrackingSettings.cs, src/SendGrid/Helpers/Mail/SendGridMessage.cs, tests/SendGrid.Tests/Integration.cs, tests/SendGrid.Tests/SendGrid.Tests.csproj
SendGrid rejects JSON containing $id and $ref properties which are added by Json.Net if reference handling is enabled. 
For projects which need this enabled it can either be disabled using a custom `ContractResolver` or annotating the objects itself with the `[JsonObject]` attribute. 
Settling this on the SendGrid Nuget side is imho cleaner and avoids trouble with future users.
It includes a test which looks for the $id/$ref properties in the serialized message. Please advise if I oversaw anything.
Issue: [#469](https://github.com/sendgrid/sendgrid-csharp/issues/469)
=> Disable Json.Net reference handling for SendGrid objects

examples/suppression/suppression.cs
// Delete a specific spam report
// DELETE /suppression/spam_reports/{email}
Needs an s on spam reports. Otherwise there will be a not found error.
=> Important Typos.

src/SendGrid/Helpers/Mail/MailHelper.cs, tests/SendGrid.Tests/Integration.cs
This pull request is related to a new overload created for `CreateSingleEmailToMultipleRecipients` method in `MailHelper.cs` class. A new parameter named `showAllRecipients` has been added which toggles the display of all the recipients in the "To" section of email. The default value of the parameter is `false` , hence the all the recipients are not shown by default in the "To" section of email.
=> Single email to multiple recipients - Toggle display of recipients

TROUBLESHOOTING.md
linked to https://stackoverflow.com/a/13494570
=> Added UI thread information

tests/SendGrid.Tests/Integration.cs
A refactor in integration tests to reduce duplication
* Removed repetition of **var host = "http://localhost:4010"** from each test
* Using **fixture.host** instead, similar to fixture.apiKey
No other changes - test tidy up only, no new package required.
=> Reduced duplication in Integration tests 

README.md
- made small phrasing changes
- updated API docs link
Also, see my comment for two sections that I think could use clarification.
=> (finally!) review readme.md getting started

ExampleCoreProject/Example.cs, ExampleNet45ASPNetProject/README.md, ExampleNet45ASPNetProject/SendGrid.ASPSamples/Service/SendGridEmailService.cs, ExampleNet45ASPNetProject/SendGrid.ASPSamples/Web.config, ExampleNet45Project/Example.cs, README.md
Issue #243:
- Updated the README with information about adding an environment variable to Windows.
- Added code comments to the console applications, refering back to the README.
- Updated the ASP.NET example to make use of an appSettings variable from the web.config
=> Added information about setting up environment variables

USAGE.md
Fixed all the Usage.md examples that were using start_time and end_time to use the same examples as in the SendGrid documentation and use unix time for those queries.
=> Update bounce usage Fixes #370

USAGE.md
This addresses #366 
Let me know if I need to add more descriptions of what HTTP status codes are!
=> Add status codes to USAGE.md

USAGE.md
Fixed the example query for list all recipients to be the same as the one in SendGrid's documentation. Removed the list_id parameter that was incorrect.
Fixes #351
=> Corrected list all recipients documentation Fixes #351

docker/Dockerfile, docker/README.md, docker/entrypoint.sh
Basic Dockerfile, based on the `dotnet:1.0-sdk` image - containing the latest version of sendgrid-csharp, as well as a running instance of prism.
Closes #535.
=> Initial dockerfile

src/SendGrid/Response.cs
Issue #455 asked to add `ConfigureAwait(false)` to the  DeserializeResponseBody's call to ReadAsStringAsync. Since that call was synchronous (with Result) the only reason to add the ConfigureAwait(false) was to make it async. This means also changing the method's name to be coherent with the rest of the library.
Fixes issue #455
=> Made DeserializeResponseBody asynchronous Fixes #455

src/SendGrid/Helpers/Mail/SendGridMessage.cs, tests/SendGrid.Tests/Integration.cs
Issue #419: PR contains changes to skip and remove `Content` objects during serialization where either the `Type` or `Value` properties are set to empty or null strings.
=> Skip invalid content objects during serialization

README.md
Changed phrasing of "just added" to "recently added".
Updated sentence structure in Getting Started section to add clarity (usage of "either" was in a single sentence so I adjusted to improve readability)
=> Minor readability fixes in README

USE_CASES.md, src/SendGrid/Helpers/Mail/SendGridMessage.cs, tests/SendGrid.Tests/Helpers/Mail/NonReadableStream.cs, tests/SendGrid.Tests/Helpers/Mail/SendGridMessageTests.cs, tests/SendGrid.Tests/Integration.cs, tests/SendGrid.Tests/Reliability/ReliabilitySettingsTests.cs
Support attachment adding via stream. I have a couple of question's I'd like to get feedback on. This ultimately addresses #511, though it doesn't add an overload for plain content being base64'd internally.
Anyway, questions:
* I chose to make the method async, because it's reading an unknown stream. Would a non-async method be desirable as well?
* The function currently just returns in several failure scenarios. It could instead return a result type value indicating status and error messages (think [IdentityResult](https://docs.microsoft.com/en-us/aspnet/core/api/microsoft.aspnetcore.identity.identityresult))
* Unit tests don't currently seem to cover this, should I add them?
* The example usage projects don't seem to show attachment handling, should I update them projects?
* [Edited] …
=> Update add attachment interface

src/SendGrid/SendGridClient.cs
Fixes  #365.
This PR changes the way QueryParams are parsed from JSON.
As JSON requires unique keys only the last value is returned in case of duplicates.
By using a `JsonTextReader` instead of `JsonConvert#DeserializeObject` this behaviour can be changed.
=> Allow for duplicate keys in QueryParams

nuspec/Sendgrid.9.9.0.nuspec, src/SendGrid/SendGrid.csproj
We don't need to reference the System.Net.Http package on .Net 4.5+ since it's provided by the framework.
I also update the targetFramework monikers to match the new ones at https://docs.microsoft.com/en-us/nuget/schema/target-frameworks
=> .Net 4.5 References

tests/SendGrid.Tests/LicenseTests.cs
- Added a unit test to check if the LICENSE.txt file contains the current year for the copyright.
=> Added test to check the license date

CONTRIBUTING.md
- I have added links to code base section of CONTRIBUTION.md so that user can directly access the files by clicking on them
=> Added links to code base in CONTRIBUTION.md

USE_CASES.md
Fix #545 as @thinkingserious suggested.
Fix #536
=> HTML to Plain text documentation

src/SendGrid/Response.cs
- There is a mixup in the inline documentation of the Response object. The summary for Response.Body says it's for the header and visa versa. This PR will fix that.
=> Fix mixup of Response.Body and Response.Header summaries

src/SendGrid/Helpers/Mail/SendGridMessage.cs
- The `SendGridMessage` has the `SetOpenTracking` which takes two arguments `enable` and `substitutionTag`. The `substitutionTag` argument is optional and if user don't want to use it currently, they need to pass null explicitly as we have it as required. So I've set it to have default `null` value.
=> #638  Add default value for SubstitutionTag parameter

.travis.yml
This PR fixes hard-coded full path in the travis build file. When someone works with the forked repository, travis builds always fail because of that.
=> Update travis config to use relative path

CONTRIBUTING.md
Updated broken links to examples
Fixes broken link to Examples
Fixes broken link to .net core example project
- Updated broken links to examples
- Updated broken links to .net core general example
=> Updated broken links to examples

README.md
Update README.md to directly link the online version of the CLA and fix the email mentions
- Directly link to the online version of the CLA (Contributor License Agreement)
- Fix email mentions similar to sendgrid-python and sendgrid-java repositories.
=> Directly link online version of CLA and fix email mentions

TROUBLESHOOTING.md
- [ x] I have made a material change to the repo (functionality, testing, spelling, grammar)
- [ x] I have read the [Contribution Guide] and my PR follows them.
- [ x] I updated my branch with the master branch.
- Fixed v3 email example broken link
=> TROUBLESHOOTING.md broken link fix

.github/PULL_REQUEST_TEMPLATE, CONTRIBUTING.md
Fixes #781
- Update CONTRIBUTING.md documentation, explaining the process of forking and branching off the development branch and submitting PRs against the development branch.
- Update PULL_REQUEST_TEMPLATE with the same addition to the CONTRIBUTING.md documentation.
=> Update documentation with new Git workflow

README.md
#813 
On the website its mentioned that Send up to 40,000 emails for 30 days, then send 100 emails/day free forever but it has not been mentioned in the README.
=>  Modification in Prerequisites for installation

src/SendGrid/SendGridClient.cs, tests/SendGrid.Tests/Integration.cs
- Remove HTTP Client Initialization 
- Setup each HTTP request with SendGrid client configuration
- Cleanup constructors
- Prefer options field over Properties
=> Refactoring SendGridClient to support inject external managed HttpClient

.travis.yml
Inspired by the kubernetes-client/csharp Travis script, I created a deploy phase that uses dotnet nuget push to deploy the package directly to NuGet when the CI is run on master.
Two configuration needs to be added, NUGET_API_KEY that is the API key for NuGet and NUGET_SOURCE that contains the NuGet package name.
It is a first proposal to fix issue #752, I will update if it doesn't fit the requirement complety.
- Adds a deploy phas to the Travis CI that publishes to NuGet
=> chore: Adds deploy phase that deploys to NuGet

.travis.yml, CHANGELOG.md, LICENSE.txt, Makefile, src/SendGrid/SendGrid.csproj
=> chore: prep the repo for automated releasing

.travis.yml, Makefile, src/SendGrid/SendGrid.csproj, tests/SendGrid.Tests/SendGrid.Tests.csproj
Fixes #972
- Updates the Travis setup to hopefully unlock assembly signing capabilities
=> fix: update setup to allow strong naming on Travis

src/SendGrid/Helpers/Mail/SendGridMessage.cs, tests/SendGrid.Tests/PreSendEmailValidation/WhenCreatingASendGridMessage.cs
Fixes #980 
When sending an email and providing an empty list of BCCs the request fails with BadRequest as outlined here: https://sendgrid.com/docs/API_Reference/Web_API_v3/Mail/errors.html#message.personalizations.bcc
We want to inform the consumer that this is the case otherwise it may lead to email sending silenty failing.
Pre send email validation to enforce the rules found here: https://sendgrid.com/docs/API_Reference/Web_API_v3/Mail/errors.html#message.personalizations.bcc
=> feat: sanity-check email address and address lists when adding to a message

src/SendGrid/SendGridClient.cs
Fixes #910 
- Removes the character set from the content headers
=> fix: Remove char set from content headers for JSON payloads

src/SendGrid/Helpers/Mail/Model/JsonConverters.cs, src/SendGrid/Helpers/Mail/Model/Personalization.cs, tests/SendGrid.Tests/Integration.cs
Fixes #691 
Closes #939
Closes #739
=> feat: ignore duplicate email addresses when serializing the message

src/SendGrid/BaseClient.cs, src/SendGrid/SendGridClient.cs
Fixes https://github.com/sendgrid/sendgrid-csharp/issues/1000
Relates to https://github.com/sendgrid/sendgrid-csharp/pull/839
When the default client options were made static and the constructors later removed, there was no way to modify the reliability settings used by the retry handler. This fix adds back the constructors so clients can now be constructed with just the client options and the options will be used when creating a retry handler, if any.
=> fix: add back client constructors with client options and actually use its reliability settings

tests/SendGrid.Tests/Integration.cs
Extending the test to ensure default serialization isn't broken.
Addressing:
https://github.com/sendgrid/sendgrid-csharp/pull/938#issuecomment-637005849
=> test: Ensuring default serialization settings behave correctly

src/SendGrid/BaseClient.cs, src/SendGrid/Helpers/Mail/Model/JsonConverters.cs, src/SendGrid/Helpers/Net40/TypeExtensions.cs, src/SendGrid/Helpers/TaskUtilities.cs, src/SendGrid/Reliability/RetryDelegatingHandler.cs, src/SendGrid/SendGrid.csproj
I saw that SendGrid.Net40 package is popular on NuGet. But, unfortunately, it has not been updated since 2015. In addition, I need this target to support the Windows XP version of the library (System.Net.Mail is available in net40, so I have to use the old method via SmtpClient). I am sure this can also help someone else.
=> feat: Added net40 target framework.

examples/eventwebhook/RequestValidator.cs, src/SendGrid/Helpers/EventWebhook/RequestValidator.cs, src/SendGrid/SendGrid.csproj, tests/SendGrid.Tests/Helpers/EventWebhook/RequestValidatorTests.cs
When enabling the "Signed Event Webhook Requests" feature in Mail Settings, Twilio SendGrid will generate a private and public key pair using the Elliptic Curve Digital Signature Algorithm (ECDSA). Once that is successfully enabled, all new event posts will have two new headers: X-Twilio-Email-Event-Webhook-Signature and X-Twilio-Email-Event-Webhook-Timestamp, which can be used to validate your events.
This SDK update will make it easier to verify signatures from signed event webhook requests by using the VerifySignature method. Pass in the public key, event payload, signature, and timestamp to validate. Note: You will need to convert your public key string to an elliptic public key object in order to use the VerifySignature method.
Fixes …
=> feat: verify signature from event webhook

USAGE.md, USE_CASES.md, examples/senderauthentication/senderauthentication.cs
Per the SendGrid Docs [here](https://github.com/sendgrid/docs/blob/develop/content/docs/glossary/whitelabel.md) as well as an upcoming addition to the Docs in a PR I have submitted [here](https://github.com/sendgrid/docs/pull/4182#discussion_r224903380), the term "Whitelabel" is no longer being used in SendGrid documentation and has been "deprecated" ([see here](https://github.com/sendgrid/docs/pull/4182#discussion_r224903380)), even though the API still references it. 
This PR alters the references to whitelabeling and replaces them with the following:
Whitelabel = Sender Authentication
Domain Whitelabel = Domain Authentication
IP Whitelabel = Reverse DNS
Link Whitelabel = Link branding
=> docs: Remove references to "Whitelabel"

src/SendGrid/BaseClient.cs, src/SendGrid/Reliability/RetryDelegatingHandler.cs, tests/SendGrid.Tests/Integration.cs
A default inner handler should not be created by the delegating handler as required by the client factory. This change moves the creation of `HttpClientHandler` to the base client.
Fixes #1026
=> feat: allow the `RetryDelegatingHandler` to be used with `HttpClientFactory`

ExampleNet45Project/Program.cs, TROUBLESHOOTING.md, src/SendGrid/SendGridClient.cs, tests/SendGrid.Tests/Integration.cs
Changes to released public method signatures are breaking changes. This fix reverts the recent constructor changes and replaces the example/tests with usage of `SendGridClientOptions` for passing the `HttpErrorAsException` flag.
Fixes #1027
=> fix: revert the 'SendGridClient' constructor changes

src/SendGrid/Helpers/Mail/MailHelper.cs
I believe there are mistakes in the documentation for creating emails in `MailHelper.cs`.
I reckon that the `from` object should represent the sender, thus there should be the sender's name instead of the recipient's name.
=> docs: fix sender email object description in MailHelper.cs

src/SendGrid/Response.cs, tests/SendGrid.Tests/Integration.cs
Resolves #1076 
Introduce new property `IsSuccessStatusCode` into `Response`. This property indicates whether given response contains success status code (2xx).
`IsSuccessStatusCode` is implemented in the same way as `HttpResponseMessage.IsSuccessStatusCode`
I could not run `make test-docker` so I made tests that are not using real requests.
=> feat: add IsSuccessStatusCode

LICENSE
feat: Add ability for Personalization to set the From Email address.
Note: The SendGrid API allows for the setting of the Personalization FromEmail and FromName but the sendgrid-csharp library does not. This small update allows these two fields to be set in the personalization.
Thank you!
Kind regards,
Joseph Little
=> feat: Add From Email to Personalization

README.md
Fixes the mistake of setting up environment variables syntax in the readme.md file
Fixes: #1099
=> docs: fix mistake in README.md

src/SendGrid/Response.cs, tests/SendGrid.Tests/ResponseTests.cs
Reverts breaking change where public method signature was changed.
Relates to #1151
=> fix: fallback to private body and headers for response deserialization

src/SendGrid/Helpers/Mail/SendGridMessage.cs, tests/SendGrid.Tests/Integration.cs, tests/SendGrid.Tests/PreSendEmailValidation/WhenCreatingASendGridMessage.cs
Closes #339
Add support to add multiple reply to email addresses.
=> feat: Add support for multiple Reply-Tos

src/SendGrid/SendGridClient.cs, tests/SendGrid.Tests/Integration.cs
When passing `httpErrorAsException` as a parameter to the `SendGridClient` constructor, it was not used for anything. This PR passes the value the the options object created.
=> fix: Use httpErrorAsException when passed as parameter to SendGridClient constructor

README.md
Adds example of configuring a WebProxy when using the DI project.
=> docs: Example of adding a WebProxy using DI

.github/workflows/test-and-deploy.yml
Updated the workflow for code signing and uploading to Nuget
=> chore: added code-signing workflow
